# Generated by Django 4.0.3 on 2022-04-05 03:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Tên'),
        ),
    ]
